#!/usr/bin/env bash
# Generated by projectsetup. This canonical installer is shared by every preset.
set -euo pipefail

fail() {
  printf 'projectsetup AI installer: %s\n' "$*" >&2
  exit 1
}

ensure_writable() {
  local path="$1"
  mkdir -p "$path" 2>/dev/null || sudo mkdir -p "$path"
  if [[ ! -w "$path" ]]; then
    sudo chown -R "$(id -u):$(id -g)" "$path"
  fi
  [[ -w "$path" ]] || fail "$path is not writable; check the host bind-mount source ownership"
}

ensure_writable "$HOME/.local"
ensure_writable "$HOME/.local/bin"
ensure_writable "$HOME/.local/state"

for tool in "$@"; do
  case "$tool" in
    opencode)
      ensure_writable "$HOME/.config/opencode"
      ensure_writable "$HOME/.local/share/opencode"
      ensure_writable "$HOME/.opencode"
      ensure_writable "$HOME/.cache/opencode"
      if ! "$HOME/.opencode/bin/opencode" --version >/dev/null 2>&1; then
        command -v curl >/dev/null 2>&1 || fail "curl is required to install OpenCode"
        curl -fsSL https://opencode.ai/install | bash || fail "OpenCode installer failed"
      fi
      [[ -x "$HOME/.opencode/bin/opencode" ]] || fail "OpenCode installer did not create ~/.opencode/bin/opencode"
      ln -sfn "$HOME/.opencode/bin/opencode" "$HOME/.local/bin/opencode"
      opencode --version >/dev/null 2>&1 || fail "OpenCode installation is not executable"
      ;;
    claude)
      ensure_writable "$HOME/.claude"
      ensure_writable "$HOME/.local/share/claude"
      export CLAUDE_CONFIG_DIR="$HOME/.claude"
      claude_binary="$(find "$HOME/.local/share/claude/versions" -mindepth 1 -maxdepth 1 -type f -executable -printf '%T@ %p\n' 2>/dev/null | sort -nr | cut -d' ' -f2- | sed -n '1p' || true)"
      if [[ -z "$claude_binary" ]] || ! "$claude_binary" --version >/dev/null 2>&1; then
        command -v curl >/dev/null 2>&1 || fail "curl is required to install Claude Code"
        curl -fsSL https://claude.ai/install.sh | bash || fail "Claude Code installer failed"
        claude_binary="$(find "$HOME/.local/share/claude/versions" -mindepth 1 -maxdepth 1 -type f -executable -printf '%T@ %p\n' 2>/dev/null | sort -nr | cut -d' ' -f2- | sed -n '1p' || true)"
      fi
      [[ -n "$claude_binary" ]] || fail "Claude installer did not create a persisted version binary"
      ln -sfn "$claude_binary" "$HOME/.local/bin/claude"
      claude --version >/dev/null 2>&1 || fail "Claude Code installation is not executable"
      ;;
    *)
      fail "unsupported AI tool: $tool"
      ;;
  esac
done
