#!/usr/bin/env bash
# Generated by projectsetup. Edit projectsetup.json and regenerate instead of editing this file.
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
"${script_dir}/install-ai-tools.sh" opencode

if [[ -f Gemfile ]]; then
  bundle install
fi
