name: Specs

on:
  push:
  pull_request:

jobs:
  license_checks:
    name: License checks
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run license checks
        run: |
          bundle exec license_finder || (cat <<-END && exit 1)

            You seem to be introducing a new license into our stack, please reach out to
            #licenses-tech-stack on slack to get guidance on the topic.
          END
